Echo Off
python enterbanktransactions_in_process.py ./data/2020_05_PNC_8_Mint_Creek.csv BWGOLDusername BWGOLDpassword
python enterbanktransactions_in_process.py ./data/2020_05_PNC_6_Mint_Creek.csv BWGOLDusername BWGOLDpassword
python enterbanktransactions_in_process.py ./data/2020_05_SBH_1_Mint_Creek.csv BWGOLDusername BWGOLDpassword
